name: run tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
        develop
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install dependencies
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
        run: |
          npm install
      - name: run tests
        run: |
          npm test
